### Mini Project --- Earthquake

# Clustering data
Dataset from Kaggle : **"Earthquake Damage Prediction"**  
Source: https://www.drivendata.org/competitions/57/nepal-earthquake/data/ (requires login)

---

### Essential Libraries

Let us begin by importing the essential Python Libraries.

> NumPy : Library for Numeric Computations in Python  
> Pandas : Library for Data Acquisition and Preparation  
> Matplotlib : Low-level library for Data Visualization  
> Seaborn : Higher-level library for Data Visualization

In [1]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

In [2]:
raw_data = pd.read_csv('train_values.csv')
##setting building_id as the index for easy referencing
raw_data = raw_data.set_index('building_id')
raw_data.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
building_id,,,,,,,,,,,,,,,,,,,,,
802906,6,487,12198,2,30,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
28830,8,900,2812,2,10,8,7,o,r,n,...,0,0,0,0,0,0,0,0,0,0
94947,21,363,8973,2,10,5,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
590882,22,418,10694,2,10,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
201944,11,131,1488,3,30,8,9,t,r,n,...,0,0,0,0,0,0,0,0,0,0

#### Reading up the data types so we are able to sort it out in terms of categorial, numerical data

In [3]:
raw_data.dtypes

geo_level_1_id                             int64
geo_level_2_id                             int64
geo_level_3_id                             int64
count_floors_pre_eq                        int64
age                                        int64
area_percentage                            int64
height_percentage                          int64
land_surface_condition                    object
foundation_type                           object
roof_type                                 object
ground_floor_type                         object
other_floor_type                          object
position                                  object
plan_configuration                        object
has_superstructure_adobe_mud               int64
has_superstructure_mud_mortar_stone        int64
has_superstructure_stone_flag              int64
has_superstructure_cement_mortar_stone     int64
has_superstructure_mud_mortar_brick        int64
has_superstructure_cement_mortar_brick     int64
has_superstructure_timber                  int64
has_superstructure_bamboo                  int64
has_superstructure_rc_non_engineered       int64
has_superstructure_rc_engineered           int64
has_superstructure_other                   int64
legal_ownership_status                    object
count_families                             int64
has_secondary_use                          int64
has_secondary_use_agriculture              int64
has_secondary_use_hotel                    int64
has_secondary_use_rental                   int64
has_secondary_use_institution              int64
has_secondary_use_school                   int64
has_secondary_use_industry                 int64
has_secondary_use_health_post              int64
has_secondary_use_gov_office               int64
has_secondary_use_use_police               int64
has_secondary_use_other                    int64
dtype: object

#### Checking for the number of values to ensure that there is no missing data

In [4]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 802906 to 747594
Data columns (total 38 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   geo_level_1_id                          260601 non-null  int64
 1   geo_level_2_id                          260601 non-null  int64
 2   geo_level_3_id                          260601 non-null  int64
 3   count_floors_pre_eq                     260601 non-null  int64
 4   age                                     260601 non-null  int64
 5   area_percentage                         260601 non-null  int64
 6   height_percentage                       260601 non-null  int64
 7   land_surface_condition                  260601 non-null  object
 8   foundation_type                         260601 non-null  object
 9   roof_type                               260601 non-null  object
 10  ground_floor_type                       260601 non-null  object
 11  other_floor_type                        260601 non-null  object
 12  position                                260601 non-null  object
 13  plan_configuration                      260601 non-null  object
 14  has_superstructure_adobe_mud            260601 non-null  int64
 15  has_superstructure_mud_mortar_stone     260601 non-null  int64
 16  has_superstructure_stone_flag           260601 non-null  int64
 17  has_superstructure_cement_mortar_stone  260601 non-null  int64
 18  has_superstructure_mud_mortar_brick     260601 non-null  int64
 19  has_superstructure_cement_mortar_brick  260601 non-null  int64
 20  has_superstructure_timber               260601 non-null  int64
 21  has_superstructure_bamboo               260601 non-null  int64
 22  has_superstructure_rc_non_engineered    260601 non-null  int64
 23  has_superstructure_rc_engineered        260601 non-null  int64
 24  has_superstructure_other                260601 non-null  int64
 25  legal_ownership_status                  260601 non-null  object
 26  count_families                          260601 non-null  int64
 27  has_secondary_use                       260601 non-null  int64
 28  has_secondary_use_agriculture           260601 non-null  int64
 29  has_secondary_use_hotel                 260601 non-null  int64
 30  has_secondary_use_rental                260601 non-null  int64
 31  has_secondary_use_institution           260601 non-null  int64
 32  has_secondary_use_school                260601 non-null  int64
 33  has_secondary_use_industry              260601 non-null  int64
 34  has_secondary_use_health_post           260601 non-null  int64
 35  has_secondary_use_gov_office            260601 non-null  int64
 36  has_secondary_use_use_police            260601 non-null  int64
 37  has_secondary_use_other                 260601 non-null  int64
dtypes: int64(30), object(8)
memory usage: 77.5+ MB

#### Damage_score calculations

In [5]:
variables_dropped = ['geo_level_1_id', 'geo_level_2_id','geo_level_3_id', 'legal_ownership_status',
                    'count_families', 'has_secondary_use', 'has_secondary_use_agriculture','has_secondary_use_hotel',
                     'has_secondary_use_rental', 'has_secondary_use_institution', 'has_secondary_use_school',
                    'has_secondary_use_industry', 'has_secondary_use_health_post','has_secondary_use_gov_office',
                    'has_secondary_use_use_police','has_secondary_use_other']
score_calculation = raw_data.drop(variables_dropped, axis=1)
score_calculation.head()

,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,...,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other
building_id,,,,,,,,,,,,,,,,,,,,,
802906,2,30,6,5,t,r,n,f,q,t,...,1,0,0,0,0,0,0,0,0,0
28830,2,10,8,7,o,r,n,x,q,s,...,1,0,0,0,0,0,0,0,0,0
94947,2,10,5,5,t,r,n,f,x,t,...,1,0,0,0,0,0,0,0,0,0
590882,2,10,6,5,t,r,n,f,x,s,...,1,0,0,0,0,1,1,0,0,0
201944,3,30,8,9,t,r,n,f,x,s,...,0,0,0,0,0,0,0,0,0,0